---
title: Evan's Cool New Internet Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/things/:path/"
email: evan@new-schmidt.com
description: 'This is Evan Lloyd New-Schmidt''s website. He goes to Olin College
  of Engineering and likes stuff.'
baseurl: ''
url: https://evan.new-schmidt.com
github_username: newsch
google_analytics: UA-104192542-2
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
